### ISSUE TITLE
No tag for released version 2.11

### ISSUE THREAD

**Issue by Stephan202** [coveooss/fmt-maven-plugin#109]
Version 2.11 of the plugin was released to [Maven Central](https://repo1.maven.org/maven2/com/coveo/fmt-maven-plugin/2.11/) on 2021-06-11, but it [appears](https://github.com/coveooss/fmt-maven-plugin/tags) that the associated tag hasn't been pushed yet. For completeness, can you please do so?

Tnx for maintaining this nice plugin!

**Comment by malaporte** [comment]
Good point, just added one!
