### ISSUE TITLE
Update to google-java-format 1.8

### ISSUE THREAD

**Issue by therealppa** [coveooss/fmt-maven-plugin#62]
There is a new release at https://github.com/google/google-java-format/releases/tag/google-java-format-1.8

It brings a few interesting changes like Java 14 support.

**Comment by therealppa** [comment]
There is already a PR for this: https://github.com/coveooss/fmt-maven-plugin/pull/61

**Comment by aaime** [comment]
Noting it also requires Java 11 to be the minimum runtime.

**Comment by malaporte** [comment]
Fixed in the latest release (2.10).
