### ISSUE TITLE
Can't build with java8 since last release

### ISSUE THREAD

**Issue by sdanelli** [coveooss/fmt-maven-plugin#63]
**Describe the bug**
We are running in java8 and getting the following problem when running a "mvn install" 

```
An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:format: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**To Reproduce**
Run `mvn clean instal` with java8 on the latest version. 

**Expected behavior**
I expected it to build like it has before, or check files properly. 

**Additional context**
Not sure if the problem is here or with "google-java-format" however starting here.

**Comment by malaporte** [comment]
Version 1.8 of Google Java Formatter no longer supports Java 8. You can use version 2.9.1 of this plugin instead.
