### ISSUE TITLE
Use log debug level for "File '...' is a directory. Skipping."

### ISSUE THREAD

**Issue by sormuras** [coveooss/fmt-maven-plugin#66]
https://github.com/coveooss/fmt-maven-plugin/blob/da9a28d5007d3dde633975275aaacd22d5bcb722/src/main/java/com/coveo/AbstractFMT.java#L205

It generates quite some `[INFO]` noise as can be seen here: https://github.com/sormuras/junit-platform-maven-plugin/runs/866055265#step:5:16 and following 83 lines.

**Comment by malaporte** [comment]
Fixed by #69
