### ISSUE TITLE
INFO test shows all the folders which are skipped in version 2.9.1

### ISSUE THREAD

**Issue by jagdeepjain** [coveooss/fmt-maven-plugin#68]
---
name: Bug report in the Maven plugin
about: Create a report to help us improve
title: 'skipping folders is not required to show in INFO logger'
labels: ''
assignees: ''

---

**Describe the bug**
INFO test shows all the folders which are skipped in version 2.9.1

**To Reproduce**
Use version 2.9.1 with a plugin as below, this will do the formatting before the code compiles but it is showing INFO for skipping folders which is unnecessary.
```
plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>2.9.1</version>
        <configuration>
          <style>google</style>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>format</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**Expected behavior**
Option to skipping folders.

**Additional context**
Better it does not shows the skipping folders INFO log.

**Comment by malaporte** [comment]
PR I just merged should address this issue, unless I'm mistaken.

**Comment by aaime** [comment]
Any chance this can get into a 2.9.2 release? Can I help?
